name: build
on: [ push ]
jobs:
  build:
    runs-on: ${{ matrix.os-name }}-latest
    strategy:
      matrix:
        os-name: [ ubuntu, macos, windows ]
    steps:
    - name: setup node
      if: ${{ matrix.os-name == 'ubuntu' }}
      shell: bash
      run: |
        curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt-get update
        sudo apt-get install -y nodejs
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
        architecture: x64
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: build
      shell: bash
      run: |
        python -m scripts build